name: Example Workflow
on:
  push:
    branches:
      - main

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set API Key as Environment Variable
        run: echo "CONTENTFUL_API_KEY=${{ secrets.CONTENTFUL_API_KEY }}" >> $GITHUB_ENV

      - name: Display API Key
        run: echo $API_KEY